### ISSUE TITLE
Introduce Modulecalls

### ISSUE THREAD

**Issue by HeikoNeblung** [terraform-docs/plugin-sdk#9]
### What problem are you facing?

I am unable to implement my PR [#367](https://github.com/terraform-docs/terraform-docs/pull/367) on terraform-docs

### How could terraform-docs help solve your problem?

Can you please introduce Modulecalls into print settings and terraform module.

**Comment by khos2ow** [comment]
@HeikoNeblung it's fine for the time being. Please proceed with rebasing https://github.com/terraform-docs/terraform-docs/pull/367 (even if CI complains of some compilation error) and then in parallel of that PR (when things get sorted out a bit more) we're going to add the changes here as well.

**Comment by khos2ow** [comment]
xref: https://github.com/terraform-docs/terraform-docs/issues/255
